// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagerAPI.Data;

#nullable disable

namespace TaskManagerAPI.Migrations
{
    [DbContext(typeof(TaskManagerAPIContext))]
    [Migration("20251215035103_Populating Table")]
    partial class PopulatingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagerAPI.Model.Tasks", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(2025, 12, 15, 3, 51, 2, 226, DateTimeKind.Utc).AddTicks(52),
                            Description = "Description for Task 1",
                            IsCompleted = false,
                            Title = "Task 1"
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(2025, 12, 15, 3, 51, 2, 226, DateTimeKind.Utc).AddTicks(1710),
                            Description = "Description for Task 2",
                            IsCompleted = false,
                            Title = "Task 2"
                        },
                        new
                        {
                            ID = 3,
                            CreatedAt = new DateTime(2025, 12, 15, 3, 51, 2, 226, DateTimeKind.Utc).AddTicks(1714),
                            Description = "Description for Task 3",
                            IsCompleted = false,
                            Title = "Task 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
